const DEFAULT_THEME = "light";

const NUMBER_OF_GUESSES = 6;

const WORD_LENGTH = 5;

const UPPERCASE_START_ASCII = 65;

const UPPERCASE_END_ASCII = 90;

const LOWERCASE_START_ASCII = 97;

const LOWERCASE_END_ASCII = 122;

export {
  DEFAULT_THEME,
  NUMBER_OF_GUESSES,
  WORD_LENGTH,
  UPPERCASE_START_ASCII,
  UPPERCASE_END_ASCII,
  LOWERCASE_START_ASCII,
  LOWERCASE_END_ASCII,
};
